@baseUrl = http://localhost:3001
# @baseUrl = https://afternoon-coast-42082.herokuapp.com
GET {{baseUrl}}/api/persons HTTP/1.1

###

GET {{baseUrl}}/info HTTP/1.1

###

GET {{baseUrl}}/api/persons/5d2439ebb1fb840fde58f1ff HTTP/1.1

###

GET {{baseUrl}}/api/persons/100 HTTP/1.1

###
@deleteId=5d25a7b4293b99219057133c
DELETE {{baseUrl}}/api/persons/{{deleteId}} HTTP/1.1

###
POST {{baseUrl}}/api/persons HTTP/1.1
content-type: application/json

{
  "name": "tim",
  "number": "1038-43804"
}
