@baseUrl=http://localhost:3003

GET {{baseUrl}}/api/blogs HTTP/1.1

###

POST {{baseUrl}}/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Flowers for Algernon",
  "author": "Charlie Gordon",
  "url": "http://algernon.com",
  "likes": 5
}

###
@blogToDelete=5d2ec398eb253b2a905726a6
DELETE {{baseUrl}}/api/blogs/{{blogToDelete}} HTTP/1.1
