@baseUrl=http://localhost:3003

GET {{baseUrl}}/api/blogs HTTP/1.1

### get specific blog

GET {{baseUrl}}/api/blogs/5d424310a6d34f17842fab64 HTTP/1.1

### update blog

PUT {{baseUrl}}/api/blogs/5d424310a6d34f17842fab64 HTTP/1.1
Content-Type: application/json

{
  "likes": 100,
  "title": "toggleable",
  "author": "works",
  "url": "yay.com",
  "user": "5d367f2b2005ec2259122f69",
  "id": "5d424310a6d34f17842fab64"
}

### new blog

POST {{baseUrl}}/api/blogs HTTP/1.1
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkMzY3ZjJiMjAwNWVjMjI1OTEyMmY2OSIsInVzZXJuYW1lIjoidGltIiwibmFtZSI6InRpbSIsImlhdCI6MTU2Mzg3MjI4MX0.TJM4eFCKZX4xTkcsrsI7B6UodeGZWqmDGbSamhp7taY

{
  "title": "Flowers for Algernon 2",
  "author": "Charlie Gordon",
  "url": "http://algernon.com",
  "likes": 5
}

### delete blog
@blogToDelete=5d36d00d58afc142ffe0757e
DELETE {{baseUrl}}/api/blogs/{{blogToDelete}} HTTP/1.1
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkMzY3ZjJiMjAwNWVjMjI1OTEyMmY2OSIsInVzZXJuYW1lIjoidGltIiwibmFtZSI6InRpbSIsImlhdCI6MTU2Mzg3MjI4MX0.TJM4eFCKZX4xTkcsrsI7B6UodeGZWqmDGbSamhp7taY

### all users
GET {{baseUrl}}/api/users HTTP/1.1

### new user
POST {{baseUrl}}/api/users HTTP/1.1
content-type: application/json

{
  "username": "tim",
  "name": "tim",
  "password": "tim"
}

### new user, insufficient password length
POST {{baseUrl}}/api/users HTTP/1.1
content-type: application/json

{
  "username": "elgar",
  "name": "eddy",
  "password": "da"
}

### login
POST {{baseUrl}}/api/login HTTP/1.1
content-type: application/json

{
  "username": "tim",
  "password": "tim"
}
